CREATE TABLE IF NOT EXISTS leopard_epochs (
    store_id   VARCHAR(26)     NOT NULL PRIMARY KEY,
    epoch      BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_at DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
