// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: leopard/v1/leopard.proto

package leopardv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Object        string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_leopard_v1_leopard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leopard_v1_leopard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_leopard_v1_leopard_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CheckRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CheckRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // "index_l1" | "index_l2" | "fga_api"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_leopard_v1_leopard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leopard_v1_leopard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_leopard_v1_leopard_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	ObjectType    string                 `protobuf:"bytes,4,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_leopard_v1_leopard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leopard_v1_leopard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_leopard_v1_leopard_proto_rawDescGZIP(), []int{2}
}

func (x *ListObjectsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ListObjectsRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListObjectsRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListObjectsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []string               `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_leopard_v1_leopard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leopard_v1_leopard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_leopard_v1_leopard_proto_rawDescGZIP(), []int{3}
}

func (x *ListObjectsResponse) GetObjects() []string {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListObjectsResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetStoreStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreStatusRequest) Reset() {
	*x = GetStoreStatusRequest{}
	mi := &file_leopard_v1_leopard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreStatusRequest) ProtoMessage() {}

func (x *GetStoreStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leopard_v1_leopard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStoreStatusRequest) Descriptor() ([]byte, []int) {
	return file_leopard_v1_leopard_proto_rawDescGZIP(), []int{4}
}

func (x *GetStoreStatusRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type GetStoreStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	CurrentEpoch  uint64                 `protobuf:"varint,2,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "master" | "replica" | "degraded"
	ShardAgeSec   int64                  `protobuf:"varint,4,opt,name=shard_age_sec,json=shardAgeSec,proto3" json:"shard_age_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreStatusResponse) Reset() {
	*x = GetStoreStatusResponse{}
	mi := &file_leopard_v1_leopard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreStatusResponse) ProtoMessage() {}

func (x *GetStoreStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leopard_v1_leopard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStoreStatusResponse) Descriptor() ([]byte, []int) {
	return file_leopard_v1_leopard_proto_rawDescGZIP(), []int{5}
}

func (x *GetStoreStatusResponse) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetStoreStatusResponse) GetCurrentEpoch() uint64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *GetStoreStatusResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetStoreStatusResponse) GetShardAgeSec() int64 {
	if x != nil {
		return x.ShardAgeSec
	}
	return 0
}

var File_leopard_v1_leopard_proto protoreflect.FileDescriptor

const file_leopard_v1_leopard_proto_rawDesc = "" +
	"\n" +
	"\x18leopard/v1/leopard.proto\x12\n" +
	"leopard.v1\x1a\x1cgoogle/api/annotations.proto\"q\n" +
	"\fCheckRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\"A\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"\x80\x01\n" +
	"\x12ListObjectsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x1f\n" +
	"\vobject_type\x18\x04 \x01(\tR\n" +
	"objectType\"G\n" +
	"\x13ListObjectsResponse\x12\x18\n" +
	"\aobjects\x18\x01 \x03(\tR\aobjects\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"2\n" +
	"\x15GetStoreStatusRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"\x90\x01\n" +
	"\x16GetStoreStatusResponse\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12#\n" +
	"\rcurrent_epoch\x18\x02 \x01(\x04R\fcurrentEpoch\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\"\n" +
	"\rshard_age_sec\x18\x04 \x01(\x03R\vshardAgeSec2\xd0\x02\n" +
	"\x0eIndexerService\x12R\n" +
	"\x05Check\x12\x18.leopard.v1.CheckRequest\x1a\x19.leopard.v1.CheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/check\x12k\n" +
	"\vListObjects\x12\x1e.leopard.v1.ListObjectsRequest\x1a\x1f.leopard.v1.ListObjectsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/list-objects\x12}\n" +
	"\x0eGetStoreStatus\x12!.leopard.v1.GetStoreStatusRequest\x1a\".leopard.v1.GetStoreStatusResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/stores/{store_id}/statusB?Z=github.com/yourorg/openfga-indexer/proto/leopard/v1;leopardv1b\x06proto3"

var (
	file_leopard_v1_leopard_proto_rawDescOnce sync.Once
	file_leopard_v1_leopard_proto_rawDescData []byte
)

func file_leopard_v1_leopard_proto_rawDescGZIP() []byte {
	file_leopard_v1_leopard_proto_rawDescOnce.Do(func() {
		file_leopard_v1_leopard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leopard_v1_leopard_proto_rawDesc), len(file_leopard_v1_leopard_proto_rawDesc)))
	})
	return file_leopard_v1_leopard_proto_rawDescData
}

var file_leopard_v1_leopard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_leopard_v1_leopard_proto_goTypes = []any{
	(*CheckRequest)(nil),           // 0: leopard.v1.CheckRequest
	(*CheckResponse)(nil),          // 1: leopard.v1.CheckResponse
	(*ListObjectsRequest)(nil),     // 2: leopard.v1.ListObjectsRequest
	(*ListObjectsResponse)(nil),    // 3: leopard.v1.ListObjectsResponse
	(*GetStoreStatusRequest)(nil),  // 4: leopard.v1.GetStoreStatusRequest
	(*GetStoreStatusResponse)(nil), // 5: leopard.v1.GetStoreStatusResponse
}
var file_leopard_v1_leopard_proto_depIdxs = []int32{
	0, // 0: leopard.v1.IndexerService.Check:input_type -> leopard.v1.CheckRequest
	2, // 1: leopard.v1.IndexerService.ListObjects:input_type -> leopard.v1.ListObjectsRequest
	4, // 2: leopard.v1.IndexerService.GetStoreStatus:input_type -> leopard.v1.GetStoreStatusRequest
	1, // 3: leopard.v1.IndexerService.Check:output_type -> leopard.v1.CheckResponse
	3, // 4: leopard.v1.IndexerService.ListObjects:output_type -> leopard.v1.ListObjectsResponse
	5, // 5: leopard.v1.IndexerService.GetStoreStatus:output_type -> leopard.v1.GetStoreStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_leopard_v1_leopard_proto_init() }
func file_leopard_v1_leopard_proto_init() {
	if File_leopard_v1_leopard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leopard_v1_leopard_proto_rawDesc), len(file_leopard_v1_leopard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leopard_v1_leopard_proto_goTypes,
		DependencyIndexes: file_leopard_v1_leopard_proto_depIdxs,
		MessageInfos:      file_leopard_v1_leopard_proto_msgTypes,
	}.Build()
	File_leopard_v1_leopard_proto = out.File
	file_leopard_v1_leopard_proto_goTypes = nil
	file_leopard_v1_leopard_proto_depIdxs = nil
}
