// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: writeproxy/v1/writeproxy.proto

package writeproxyv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TupleKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleKey) Reset() {
	*x = TupleKey{}
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleKey) ProtoMessage() {}

func (x *TupleKey) ProtoReflect() protoreflect.Message {
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleKey.ProtoReflect.Descriptor instead.
func (*TupleKey) Descriptor() ([]byte, []int) {
	return file_writeproxy_v1_writeproxy_proto_rawDescGZIP(), []int{0}
}

func (x *TupleKey) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TupleKey) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *TupleKey) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type WriteTuplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Writes        []*TupleKey            `protobuf:"bytes,2,rep,name=writes,proto3" json:"writes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTuplesRequest) Reset() {
	*x = WriteTuplesRequest{}
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTuplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTuplesRequest) ProtoMessage() {}

func (x *WriteTuplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTuplesRequest.ProtoReflect.Descriptor instead.
func (*WriteTuplesRequest) Descriptor() ([]byte, []int) {
	return file_writeproxy_v1_writeproxy_proto_rawDescGZIP(), []int{1}
}

func (x *WriteTuplesRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *WriteTuplesRequest) GetWrites() []*TupleKey {
	if x != nil {
		return x.Writes
	}
	return nil
}

type WriteTuplesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTuplesResponse) Reset() {
	*x = WriteTuplesResponse{}
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTuplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTuplesResponse) ProtoMessage() {}

func (x *WriteTuplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTuplesResponse.ProtoReflect.Descriptor instead.
func (*WriteTuplesResponse) Descriptor() ([]byte, []int) {
	return file_writeproxy_v1_writeproxy_proto_rawDescGZIP(), []int{2}
}

type DeleteTuplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Deletes       []*TupleKey            `protobuf:"bytes,2,rep,name=deletes,proto3" json:"deletes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTuplesRequest) Reset() {
	*x = DeleteTuplesRequest{}
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTuplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTuplesRequest) ProtoMessage() {}

func (x *DeleteTuplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTuplesRequest.ProtoReflect.Descriptor instead.
func (*DeleteTuplesRequest) Descriptor() ([]byte, []int) {
	return file_writeproxy_v1_writeproxy_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTuplesRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *DeleteTuplesRequest) GetDeletes() []*TupleKey {
	if x != nil {
		return x.Deletes
	}
	return nil
}

type DeleteTuplesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTuplesResponse) Reset() {
	*x = DeleteTuplesResponse{}
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTuplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTuplesResponse) ProtoMessage() {}

func (x *DeleteTuplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTuplesResponse.ProtoReflect.Descriptor instead.
func (*DeleteTuplesResponse) Descriptor() ([]byte, []int) {
	return file_writeproxy_v1_writeproxy_proto_rawDescGZIP(), []int{4}
}

type WriteAuthorizationModelRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StoreId         string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	ModelDefinition []byte                 `protobuf:"bytes,2,opt,name=model_definition,json=modelDefinition,proto3" json:"model_definition,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WriteAuthorizationModelRequest) Reset() {
	*x = WriteAuthorizationModelRequest{}
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAuthorizationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAuthorizationModelRequest) ProtoMessage() {}

func (x *WriteAuthorizationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAuthorizationModelRequest.ProtoReflect.Descriptor instead.
func (*WriteAuthorizationModelRequest) Descriptor() ([]byte, []int) {
	return file_writeproxy_v1_writeproxy_proto_rawDescGZIP(), []int{5}
}

func (x *WriteAuthorizationModelRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *WriteAuthorizationModelRequest) GetModelDefinition() []byte {
	if x != nil {
		return x.ModelDefinition
	}
	return nil
}

type WriteAuthorizationModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAuthorizationModelResponse) Reset() {
	*x = WriteAuthorizationModelResponse{}
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAuthorizationModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAuthorizationModelResponse) ProtoMessage() {}

func (x *WriteAuthorizationModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_writeproxy_v1_writeproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAuthorizationModelResponse.ProtoReflect.Descriptor instead.
func (*WriteAuthorizationModelResponse) Descriptor() ([]byte, []int) {
	return file_writeproxy_v1_writeproxy_proto_rawDescGZIP(), []int{6}
}

func (x *WriteAuthorizationModelResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

var File_writeproxy_v1_writeproxy_proto protoreflect.FileDescriptor

const file_writeproxy_v1_writeproxy_proto_rawDesc = "" +
	"\n" +
	"\x1ewriteproxy/v1/writeproxy.proto\x12\rwriteproxy.v1\x1a\x1cgoogle/api/annotations.proto\"R\n" +
	"\bTupleKey\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\"`\n" +
	"\x12WriteTuplesRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12/\n" +
	"\x06writes\x18\x02 \x03(\v2\x17.writeproxy.v1.TupleKeyR\x06writes\"\x15\n" +
	"\x13WriteTuplesResponse\"c\n" +
	"\x13DeleteTuplesRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x121\n" +
	"\adeletes\x18\x02 \x03(\v2\x17.writeproxy.v1.TupleKeyR\adeletes\"\x16\n" +
	"\x14DeleteTuplesResponse\"f\n" +
	"\x1eWriteAuthorizationModelRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12)\n" +
	"\x10model_definition\x18\x02 \x01(\fR\x0fmodelDefinition\"<\n" +
	"\x1fWriteAuthorizationModelResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId2\xc6\x03\n" +
	"\x11WriteProxyService\x12|\n" +
	"\vWriteTuples\x12!.writeproxy.v1.WriteTuplesRequest\x1a\".writeproxy.v1.WriteTuplesResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/stores/{store_id}/write\x12\x80\x01\n" +
	"\fDeleteTuples\x12\".writeproxy.v1.DeleteTuplesRequest\x1a#.writeproxy.v1.DeleteTuplesResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/stores/{store_id}/delete\x12\xaf\x01\n" +
	"\x17WriteAuthorizationModel\x12-.writeproxy.v1.WriteAuthorizationModelRequest\x1a..writeproxy.v1.WriteAuthorizationModelResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/stores/{store_id}/authorization-modelsBEZCgithub.com/yourorg/openfga-indexer/proto/writeproxy/v1;writeproxyv1b\x06proto3"

var (
	file_writeproxy_v1_writeproxy_proto_rawDescOnce sync.Once
	file_writeproxy_v1_writeproxy_proto_rawDescData []byte
)

func file_writeproxy_v1_writeproxy_proto_rawDescGZIP() []byte {
	file_writeproxy_v1_writeproxy_proto_rawDescOnce.Do(func() {
		file_writeproxy_v1_writeproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_writeproxy_v1_writeproxy_proto_rawDesc), len(file_writeproxy_v1_writeproxy_proto_rawDesc)))
	})
	return file_writeproxy_v1_writeproxy_proto_rawDescData
}

var file_writeproxy_v1_writeproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_writeproxy_v1_writeproxy_proto_goTypes = []any{
	(*TupleKey)(nil),                        // 0: writeproxy.v1.TupleKey
	(*WriteTuplesRequest)(nil),              // 1: writeproxy.v1.WriteTuplesRequest
	(*WriteTuplesResponse)(nil),             // 2: writeproxy.v1.WriteTuplesResponse
	(*DeleteTuplesRequest)(nil),             // 3: writeproxy.v1.DeleteTuplesRequest
	(*DeleteTuplesResponse)(nil),            // 4: writeproxy.v1.DeleteTuplesResponse
	(*WriteAuthorizationModelRequest)(nil),  // 5: writeproxy.v1.WriteAuthorizationModelRequest
	(*WriteAuthorizationModelResponse)(nil), // 6: writeproxy.v1.WriteAuthorizationModelResponse
}
var file_writeproxy_v1_writeproxy_proto_depIdxs = []int32{
	0, // 0: writeproxy.v1.WriteTuplesRequest.writes:type_name -> writeproxy.v1.TupleKey
	0, // 1: writeproxy.v1.DeleteTuplesRequest.deletes:type_name -> writeproxy.v1.TupleKey
	1, // 2: writeproxy.v1.WriteProxyService.WriteTuples:input_type -> writeproxy.v1.WriteTuplesRequest
	3, // 3: writeproxy.v1.WriteProxyService.DeleteTuples:input_type -> writeproxy.v1.DeleteTuplesRequest
	5, // 4: writeproxy.v1.WriteProxyService.WriteAuthorizationModel:input_type -> writeproxy.v1.WriteAuthorizationModelRequest
	2, // 5: writeproxy.v1.WriteProxyService.WriteTuples:output_type -> writeproxy.v1.WriteTuplesResponse
	4, // 6: writeproxy.v1.WriteProxyService.DeleteTuples:output_type -> writeproxy.v1.DeleteTuplesResponse
	6, // 7: writeproxy.v1.WriteProxyService.WriteAuthorizationModel:output_type -> writeproxy.v1.WriteAuthorizationModelResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_writeproxy_v1_writeproxy_proto_init() }
func file_writeproxy_v1_writeproxy_proto_init() {
	if File_writeproxy_v1_writeproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_writeproxy_v1_writeproxy_proto_rawDesc), len(file_writeproxy_v1_writeproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_writeproxy_v1_writeproxy_proto_goTypes,
		DependencyIndexes: file_writeproxy_v1_writeproxy_proto_depIdxs,
		MessageInfos:      file_writeproxy_v1_writeproxy_proto_msgTypes,
	}.Build()
	File_writeproxy_v1_writeproxy_proto = out.File
	file_writeproxy_v1_writeproxy_proto_goTypes = nil
	file_writeproxy_v1_writeproxy_proto_depIdxs = nil
}
