// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: writeproxy/v1/writeproxy.proto

package writeproxyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WriteProxyService_WriteTuples_FullMethodName             = "/writeproxy.v1.WriteProxyService/WriteTuples"
	WriteProxyService_DeleteTuples_FullMethodName            = "/writeproxy.v1.WriteProxyService/DeleteTuples"
	WriteProxyService_WriteAuthorizationModel_FullMethodName = "/writeproxy.v1.WriteProxyService/WriteAuthorizationModel"
)

// WriteProxyServiceClient is the client API for WriteProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WriteProxyServiceClient interface {
	WriteTuples(ctx context.Context, in *WriteTuplesRequest, opts ...grpc.CallOption) (*WriteTuplesResponse, error)
	DeleteTuples(ctx context.Context, in *DeleteTuplesRequest, opts ...grpc.CallOption) (*DeleteTuplesResponse, error)
	WriteAuthorizationModel(ctx context.Context, in *WriteAuthorizationModelRequest, opts ...grpc.CallOption) (*WriteAuthorizationModelResponse, error)
}

type writeProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWriteProxyServiceClient(cc grpc.ClientConnInterface) WriteProxyServiceClient {
	return &writeProxyServiceClient{cc}
}

func (c *writeProxyServiceClient) WriteTuples(ctx context.Context, in *WriteTuplesRequest, opts ...grpc.CallOption) (*WriteTuplesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteTuplesResponse)
	err := c.cc.Invoke(ctx, WriteProxyService_WriteTuples_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeProxyServiceClient) DeleteTuples(ctx context.Context, in *DeleteTuplesRequest, opts ...grpc.CallOption) (*DeleteTuplesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTuplesResponse)
	err := c.cc.Invoke(ctx, WriteProxyService_DeleteTuples_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeProxyServiceClient) WriteAuthorizationModel(ctx context.Context, in *WriteAuthorizationModelRequest, opts ...grpc.CallOption) (*WriteAuthorizationModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteAuthorizationModelResponse)
	err := c.cc.Invoke(ctx, WriteProxyService_WriteAuthorizationModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriteProxyServiceServer is the server API for WriteProxyService service.
// All implementations must embed UnimplementedWriteProxyServiceServer
// for forward compatibility.
type WriteProxyServiceServer interface {
	WriteTuples(context.Context, *WriteTuplesRequest) (*WriteTuplesResponse, error)
	DeleteTuples(context.Context, *DeleteTuplesRequest) (*DeleteTuplesResponse, error)
	WriteAuthorizationModel(context.Context, *WriteAuthorizationModelRequest) (*WriteAuthorizationModelResponse, error)
	mustEmbedUnimplementedWriteProxyServiceServer()
}

// UnimplementedWriteProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWriteProxyServiceServer struct{}

func (UnimplementedWriteProxyServiceServer) WriteTuples(context.Context, *WriteTuplesRequest) (*WriteTuplesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteTuples not implemented")
}
func (UnimplementedWriteProxyServiceServer) DeleteTuples(context.Context, *DeleteTuplesRequest) (*DeleteTuplesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTuples not implemented")
}
func (UnimplementedWriteProxyServiceServer) WriteAuthorizationModel(context.Context, *WriteAuthorizationModelRequest) (*WriteAuthorizationModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteAuthorizationModel not implemented")
}
func (UnimplementedWriteProxyServiceServer) mustEmbedUnimplementedWriteProxyServiceServer() {}
func (UnimplementedWriteProxyServiceServer) testEmbeddedByValue()                           {}

// UnsafeWriteProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WriteProxyServiceServer will
// result in compilation errors.
type UnsafeWriteProxyServiceServer interface {
	mustEmbedUnimplementedWriteProxyServiceServer()
}

func RegisterWriteProxyServiceServer(s grpc.ServiceRegistrar, srv WriteProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedWriteProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WriteProxyService_ServiceDesc, srv)
}

func _WriteProxyService_WriteTuples_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteTuplesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteProxyServiceServer).WriteTuples(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteProxyService_WriteTuples_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteProxyServiceServer).WriteTuples(ctx, req.(*WriteTuplesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteProxyService_DeleteTuples_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTuplesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteProxyServiceServer).DeleteTuples(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteProxyService_DeleteTuples_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteProxyServiceServer).DeleteTuples(ctx, req.(*DeleteTuplesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteProxyService_WriteAuthorizationModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteAuthorizationModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteProxyServiceServer).WriteAuthorizationModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteProxyService_WriteAuthorizationModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteProxyServiceServer).WriteAuthorizationModel(ctx, req.(*WriteAuthorizationModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WriteProxyService_ServiceDesc is the grpc.ServiceDesc for WriteProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WriteProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "writeproxy.v1.WriteProxyService",
	HandlerType: (*WriteProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteTuples",
			Handler:    _WriteProxyService_WriteTuples_Handler,
		},
		{
			MethodName: "DeleteTuples",
			Handler:    _WriteProxyService_DeleteTuples_Handler,
		},
		{
			MethodName: "WriteAuthorizationModel",
			Handler:    _WriteProxyService_WriteAuthorizationModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "writeproxy/v1/writeproxy.proto",
}
